Auto-Committed-Bash:  ver: 2.1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 # Configuration script for GNU CC
-#   Copyright (C) 1988, 1990, 1991 Free Software Foundation, Inc.
+#   Copyright (C) 1988, 1990, 1991, 1992 Free Software Foundation, Inc.
 
 #This file is part of GNU CC.
 
@@ -42,6 +42,7 @@ fi
 remove=rm
 hard_link=ln
 symbolic_link='ln -s'
+copy=cp
 
 # Record all the arguments, to write them in config.status.
 arguments=$*
@@ -56,8 +57,6 @@ do
 # Handle -srcdir, etc, with space between it and argument.
   if [ x$next_srcdir = xyes ]
   then srcdir=$arg; next_srcdir=;
-  else if [ x$next_objdir = xyes ]
-  then objdir=$arg; next_objdir=;
 # Handle -host, etc, with space between it and argument.
   else if [ x$next_host = xyes ]
   then host=$arg; next_host=;
@@ -70,12 +69,6 @@ do
 	;;
      -srcdir | --srcdir | --srcdi | --srcd | --src | --sr | --s)
 	next_srcdir=yes
-	;;
-     -objdir=* | --objdir=* | --objdi=* | --objd=* | --obj=* | --ob=* | --o=*)
-	objdir=`echo $arg | sed 's/-*o[a-z]*=//'`
-	;;
-     -objdir | --objdir | --objdi | --objd | --obj | --ob | --o)
-	next_objdir=yes
 	;;
      -host | --host | --hos | --ho | --h)
 	next_host=yes
@@ -95,6 +88,7 @@ do
      -nfp | --nfp | --nf | --n)
 	nfp=yes
 	;;
+     -x | --x) ;; # ignored
      *)
 # Allow configure HOST TARGET
 	if [ x$host = x ]
@@ -104,7 +98,7 @@ do
 	target=$arg
 	;;
     esac
-  fi; fi; fi; fi
+  fi; fi; fi
 done
 
 # Find the source files, if location was not specified.
@@ -122,34 +116,29 @@ if [ ! -r ${srcdir}/tree.c ]
 then
 	if [ x$srcdirdefaulted = x ]
 	then
-	  echo "$progname: Can't find compiler sources in \`${srcdir}'." 1>&2
+	  echo "$progname: Can't find compiler sources in \`${srcdir}'" 1>&2
 	else
-	  echo "$progname: Can't find compiler sources in \`.' or \`..'." 1>&2
+	  echo "$progname: Can't find compiler sources in \`.' or \`..'" 1>&2
 	fi
 	exit 1
 fi
 
-# If the directory for object files was specified, 
-# go to that directory and do the configuring there.
-# Replace srcdir with an absolute file name
-# so that changing working directory does not invalidate it.
-if [ x$objdir = x ]
-then true
-else
-	srcdir=`(cd $srcdir; pwd)`
-	cd $objdir
+if [ -r ${srcdir}/config.status ] && [ x$srcdir != x. ]
+then
+	echo "$progname: \`configure' has been run in \`${srcdir}'" 1>&2
+	exit 1
 fi
 
 # Complain if an arg is missing
 if [ x$target = x ]
 then
-	echo "No target specified."
-	echo "Usage: $progname [--srcdir=DIR] [--host=HOST] [--gas] [--nfp] TARGET"
-	echo -n "Where HOST and TARGET are something like "
-	echo "\`vax', \`sun3', \`encore', etc."
+	echo "No target specified." 1>&2
+	echo "Usage: $progname [--srcdir=DIR] [--host=HOST] [--gas] [--nfp] TARGET" 1>&2
+	echo -n "Where HOST and TARGET are something like " 1>&2
+	echo "\`vax', \`sun3', \`encore', etc." 1>&2
 	if [ -r config.status ]
 	then
-		cat config.status
+		cat config.status 1>&2
 	fi
 	exit 1
 fi
@@ -219,7 +208,17 @@ for machine in $host $target; do
 		;;
 	i386-sequent-bsd*) 		# 80386 from Sequent
 		xm_file=xm-i386.h
-		tm_file=seq386.h
+		if [ x$gas = xyes ]
+		then
+			tm_file=seq386gas.h
+		else
+			tm_file=seq386.h
+		fi
+		;;
+	i386-*-bsd)
+		xm_file=xm-i386.h
+		tm_file=i386bsd.h
+		tmake_file=t-libc-ok
 		;;
 	i386-*-mach*)
 		xm_file=xm-i386.h
@@ -227,15 +226,16 @@ for machine in $host $target; do
 		tmake_file=t-libc-ok
 		;;
 	i386-*-sco*)		 	# 80386 running SCO system
-		xm_file=xm-i386v.h
+		xm_file=xm-i386sco.h
 		tm_file=i386sco.h
 		xmake_file=x-i386sco
 		tmake_file=t-i386sco
 		;;
 	i386-*-isc*)			# 80386 running ISC system
-		xm_file=xm-i386v.h
+		xm_file=xm-i386isc.h
 		tm_file=i386isc.h
 		xmake_file=x-i386isc
+		tmake_file=t-i386isc
 		;;
 	i386-ibm-aix*)			# IBM PS/2 running AIX
 		tm_file=aix386.h
@@ -296,7 +296,7 @@ for machine in $host $target; do
 			tm_file=i860b.h
 		fi
 		;;
-	sparc-unicom-*)
+	sparc-tti-*)
 		tm_file=pbd.h
 		xm_file=xm-pbd.h
 		;;
@@ -307,19 +307,11 @@ for machine in $host $target; do
 		tm_file=sun4o3.h
 		;;
 	sparc-*-sysv4*)
-		tm_file=sparc.h
+		xm_file=xm-sparcv4.h
+		tm_file=sparcv4.h
 		tmake_file=t-svr4
+		xmake_file=x-sparcv4
 		;;
-	m68k-tti-*)
-		tm_file=tti68k.h
-		;;
-# This has not been updated in a while.  I don't think it will be.
-# mab@tticda.tti.com might be able to say more.  If it does not get
-# updated, the newpbb.h file can be yanked, as it is not for a
-# general machine.  Mike Stump <mrs@csun.edu>.
-#	m68k-tti2-*)
-#		tm_file=newpbb.h
-#		;;
 	m68k-*-amix*)		# Commodore variant of V.4.
 		tm_file=amix.h
 		xm_file=xm-amix.h
@@ -336,7 +328,7 @@ for machine in $host $target; do
 		tm_file=next.h
 		out_file=next.c
 		xm_file=xm-next.h
-		tmake_file=t-libc-ok
+		tmake_file=t-next
 		;;
 	m68k-sun-sunos3*)
 		if [ x$nfp = xyes ]
@@ -346,16 +338,20 @@ for machine in $host $target; do
 			tm_file=sun3o3.h
 		fi
 		;;
-	m68k-sun-mach*)
-		tm_file=sun3mach.h
-		;;
-	m68k-sun-sunos4*)
+	m68k-sun-sunos*)		# For Sunos 4 (the default).
 		if [ x$nfp = xyes ]
 		then
 			tm_file=sun3n.h
 		else
 			tm_file=sun3.h
 		fi
+		;;
+	m68k-sun-mach*)
+		tm_file=sun3mach.h
+		;;
+	m68k-tti-*)
+		tm_file=pbb.h
+		xm_file=xm-m68kv.h
 		;;
 	m68k-hp-hpux*)	# HP 9000 series 300
 		xm_file=xm-hp320.h
@@ -475,6 +471,13 @@ for machine in $host $target; do
 	ns32k-merlin-*)
 		tm_file=merlin.h
 		;;
+	ns32k-pc532-mach*)
+		tm_file=pc532-mach.h
+		;;
+	ns32k-pc532-minix*)
+		tm_file=pc532-min.h
+		xm_file=xm-pc532-min.h
+		;;
 	m88k-*-luna*)
 		tm_file=m88kluna.h
 		xmake_file=x-m88kluna
@@ -490,13 +493,14 @@ for machine in $host $target; do
 		tmake_file=t-m88kv4
 		tm_file=m88kv4.h
 		;;
+	m88k-dolphin-sysv3*)
+		tm_file=m88kdolph.h
+		xm_file=xm-m88kv3.h
+		xmake_file=x-m88kdolph
+		;;
 	m88k-*-sysv3*)
 		tm_file=m88kv3.h
 		xm_file=xm-m88kv3.h
-		;;
-	m88k-*)
-		tm_file=m88k.h
-		xm_file=xm-m88k.h
 		;;
 # This hasn't been upgraded to GCC 2.
 #	fx80-alliant-*)			# Alliant FX/80
@@ -529,15 +533,23 @@ for machine in $host $target; do
 		tm_file=iris.h
 		xm_file=xm-irix4.h
 		install_with_cp=yes
+		xmake_file=x-iris
 		;;
-	mips-sgi-irix*)			# Mostly like a MIPS.
+	mips-sgi*)			# Mostly like a MIPS.
 		tm_file=iris.h
 		xm_file=xm-iris.h
 		install_with_cp=yes
+		xmake_file=x-iris
 		;;
-	mips-*-sysv)			# MIPS System V.
+	mips-*-sysv4*)			# MIPS System V.4.
+		tm_file=mips-svr4.h
+		xm_file=xm-umips.h
+		xmake_file=x-mipsv
+		;;
+	mips-*-sysv*)			# MIPS System V.
 		tm_file=mips-sysv.h
 		xm_file=xm-umips.h
+		xmake_file=x-mipsv
 		;;
 	mips-mips-*)			# Default MIPS environment.
 		tm_file=mips.h
@@ -545,19 +557,27 @@ for machine in $host $target; do
 	mips-dec-ultrix*)		# Decstation.
 		tm_file=decstatn.h
 		tmake_file=t-decstatn
+		xmake_file=x-decstatn
 	        ;;
-	mips-dec-osf*)			# Decstation with OSF/1.
+	mips-dec-osf*)			# Decstation running OSF/1 reference port with OSF/rose.
 		tm_file=decrose.h
 		xmake_file=x-decrose
 		tmake_file=t-decrose
 		;;
-	mips-sony-bsd*)	# Sony NEWS 3600 or risc/news.
+	mips-sony-bsd*)			# Sony NEWS 3600 or risc/news.
 		tm_file=mips-news.h
 		;;
-	mips-*-bsd*)	# BSD 4.3 variant of MIPS system.
+	mips-sony-sysv*)		# Sony NEWS 3800 with NEWSOS5.0.
+					# That is based on svr4.
+		# t-svr4 is not right because this system doesn't use ELF.
+		tm_file=mips-news5.h
+		xm_file=xm-mipsnews.h
+		;;
+	mips-*-bsd*)			# BSD 4.3 variant of MIPS system.
 		tm_file=mips-bsd.h
 	        ;;
-# This hasn't been upgraded to GCC 2.
+# This port has been upgraded and is almost working.
+# Turn it back on if you would like to help debug it.
 #	pyramid | pyramid-* | pyramid-*)
 #		cpu_type=pyr
 #		tm_file=pyr.h
@@ -572,7 +592,7 @@ for machine in $host $target; do
 		xm_file=xm-a29kunix.h
 		xmake_file=x-a29kunix
 		;;
-	romp-*-bsd*)
+	romp-*-aos*)
 		xm_file=xm-romp.h
 		tm_file=romp.h
 		;;
@@ -584,15 +604,27 @@ for machine in $host $target; do
 	rs6000-*-mach* | rs6000-mach*)
 		xm_file=xm-rs6k-m.h
 		tm_file=rs6000-mach.h
+		tmake_file=t-rs6000
 		;;
 	rs6000-*)
 		xm_file=xm-rs6000.h
 		tm_file=rs6000.h
+		tmake_file=t-rs6000
 		;;
-	hp800-*-* | hp700-*-*)
+	hp800-*-bsd* | hp700-*-bsd*)
 		cpu_type=hp800
 		xm_file=xm-hp800.h
 		tm_file=hp800.h
+		;;
+	hp800-*-hpux* | hp700-*-hpux*)
+		cpu_type=hp800
+		xm_file=xm-hp800.h
+		tm_file=hp800hpux.h
+		xmake_file=x-hp800hpux
+		;;
+	*)
+		echo "Configuration $machine not recognized" 1>&2
+		exit 1
 		;;
 	esac
 
@@ -658,21 +690,21 @@ do
 	if [ ! -r ${srcdir}/config/$file ]
 	then
 		echo "$progname: cannot create a link \`$link'," 1>&2
-		echo "since the file \`config/$file' does not exist." 1>&2
+		echo "since the file \`config/$file' does not exist" 1>&2
 		exit 1
 	fi
 
 	$remove -f $link
 	rm -f config.status
 	# Make a symlink if possible, otherwise try a hard link
-	$symbolic_link ${srcdir}/config/$file $link 2>/dev/null || $hard_link ${srcdir}/config/$file $link
+	$symbolic_link ${srcdir}/config/$file $link 2>/dev/null || $hard_link ${srcdir}/config/$file $link || $copy ${srcdir}/config/$file $link
 
 	if [ ! -r $link ]
 	then
-		echo "$progname: unable to link \`$link' to \`${srcdir}/config/$file'." 1>&2
+		echo "$progname: unable to link \`$link' to \`${srcdir}/config/$file'" 1>&2
 		exit 1
 	fi
-	echo "Linked \`$link' to \`${srcdir}/config/$file'."
+	echo "Linked \`$link' to \`${srcdir}/config/$file'"
 done
 
 # Create Makefile.tem from Makefile.in.
diff --git a/fixincludes b/fixincludes
--- a/fixincludes
+++ b/fixincludes
@@ -2,8 +2,6 @@
 # Install modified versions of certain ANSI-incompatible system header files
 # which are fixed to work correctly with ANSI C
 # and placed in a directory that GNU C will search.
-# This works properly on a Sun in system version 3.4;
-# for other versions, you had better check.
 
 # See README-fixinc for more information.
 
@@ -45,11 +43,9 @@ fi
 
 echo 'Making directories:'
 cd ${INPUT}
-if $LINKS; then
-  files=`ls -LR | sed -n s/:$//p`
-else
-  files=`find . -type d -print | sed '/^.$/d'`
-fi
+# Find all directories and all symlinks that point to directories.
+files=`	find . -type d -print | sed '/^.$/d'
+	$LINKS && find . -type l -exec test -d '{}' \; -print`
 for file in $files; do
   rm -rf $LIB/$file
   if [ ! -d $LIB/$file ]
@@ -112,14 +108,21 @@ while [ $# != 0 ]; do
   for file in $files; do
 # This call to egrep is essential, since checking a file with egrep
 # is much faster than actually trying to fix it.
+# It is also essential that most files *not* match!
+# Thus, matching every #endif is unacceptable.
 # But the argument to egrep must be kept small, or many versions of egrep
 # won't be able to handle it.
+# rms: I removed `|#[el].*if.*[^/ 	]' because it made egrep fail.
     if egrep '[ 	_]_IO|CTRL|#define.NULL|#[el]*if.*([0-9]|sparc|vax|sun|pyr)' $file > /dev/null; then
       echo Fixing $file
       if [ -r $file ]; then
 	cp $file $2/$file >/dev/null 2>&1	\
 	|| echo "Can't copy $file"
 	chmod +w $2/$file
+# Following two lines removed.
+#	  s%^\([ 	]*#[ 	]*endif[ 	]*\)\([^/ 	].*\)$%\1/* \2 */%
+#	  s%^\([ 	]*#[ 	]*else[ 	]*\)\([^/ 	].*\)$%\1/* \2 */%
+
 	sed -e '
 				   :loop
 	  /\\$/			N
@@ -132,22 +135,17 @@ while [ $# != 0 ]; do
 	  /#define.CTRL/		s/'\''c'\''/c/g
 	  /#define._CTRL/		s/'\''c'\''/c/g
 	  /#define.BSD43_CTRL/		s/'\''c'\''/c/g
-	  /#[a-z]*if.*[ (]m68k/		s/m68k/__m68k__/g
-	  /#[a-z]*if.*[ (]__i386/	s/__i386/__i386__/g
-	  /#[a-z]*if.*[ (]i386/		s/i386/__i386__/g
-	  /#[a-z]*if.*[ (]sparc/	s/sparc/__sparc__/g
-	  /#[a-z]*if.*[ (]mc68000/	s/mc68000/__mc68000__/g
-	  /#[a-z]*if.*[ (]vax/		s/vax/__vax__/g
-	  /#[a-z]*if.*[ (]sun3x/	s/sun3x/__sun3x__/g
-	  /#[a-z]*if.*[ (]sun3/		s/sun3/__sun3__/g
-	  /#[a-z]*if.*[ (]sun2/		s/sun2/__sun2__/g
-	  /#[a-z]*if.*[ (]sun4c/	s/sun4c/__sun4c__/g
-	  /#[a-z]*if.*[ (]sun4/		s/sun4/__sun4__/g
-	  /#[a-z]*if.*[ (]sun/		s/sun/__sun__/g
-	  /#[a-z]*if.*[ (]ns32000/	s/ns32000/__ns32000__/g
-	  /#[a-z]*if.*[ (]pyr/		s/pyr/__pyr__/g
-	  /#[a-z]*if.*[ (]is68k/	s/is68k/__is68k__/g
-	  /#[a-z]*if.*[ (]sun386/	s/sun386/__sun386__/g
+	  /#[a-z]*if.*[	 (]m68k/		s/\([^_]\)m68k/\1__m68k__/g
+	  /#[a-z]*if.*[	 (]__i386/	s/__i386/__i386__/g
+	  /#[a-z]*if.*[	 (]i386/		s/\([^_]\)i386/\1__i386__/g
+	  /#[a-z]*if.*[	 (]sparc/	s/\([^_]\)sparc/\1__sparc__/g
+	  /#[a-z]*if.*[	 (]mc68000/	s/\([^_]\)mc68000/\1__mc68000__/g
+	  /#[a-z]*if.*[	 (]vax/		s/\([^_]\)vax/\1__vax__/g
+	  /#[a-z]*if.*[	 (]sun/		s/\([^_]\)\(sun[a-z0-9]*\)\([^a-z0-9_]\)/\1__\2__\3/g
+	  /#[a-z]*if.*[	 (]sun/		s/\([^_]\)\(sun[a-z0-9]*\)$/\1__\2__/g
+	  /#[a-z]*if.*[	 (]ns32000/	s/\([^_]\)ns32000/\1__ns32000__/g
+	  /#[a-z]*if.*[	 (]pyr/		s/\([^_]\)pyr/\1__pyr__/g
+	  /#[a-z]*if.*[	 (]is68k/	s/\([^_]\)is68k/\1__is68k__/g
 	  /#define.NULL[ 	]/	i\
 		#undef NULL
 	' $2/$file > $2/$file.sed
@@ -166,12 +164,10 @@ cd ${INPUT}
 
 # Fix one other error in this file: a mismatched quote not inside a C comment.
 file=sundev/vuid_event.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/sundev 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
@@ -187,23 +183,19 @@ EOF
 fi
 
 # Fix this Sun file to avoid intefering with stddef.h.
-
 file=sys/stdtypes.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
-  echo Fixing $file comment
+  echo Fixing $file
   ex ${LIB}/$file <<EOF
   /size_t.*;/
   i
-#ifndef _SIZE_T
-#define _SIZE_T
+#ifndef _GCC_SIZE_T
+#define _GCC_SIZE_T
 .
   /size_t/+1
   i
@@ -211,8 +203,8 @@ if [ -r ${LIB}/$file ]; then
 .
   /ptrdiff_t.*;/
   i
-#ifndef _PTRDIFF_T
-#define _PTRDIFF_T
+#ifndef _GCC_PTRDIFF_T
+#define _GCC_PTRDIFF_T
 .
   /ptrdiff_t/+1
   i
@@ -220,8 +212,8 @@ if [ -r ${LIB}/$file ]; then
 .
   /wchar_t.*;/
   i
-#ifndef _WCHAR_T
-#define _WCHAR_T
+#ifndef _GCC_WCHAR_T
+#define _GCC_WCHAR_T
 .
   /wchar_t/+1
   i
@@ -236,23 +228,19 @@ EOF
 fi
 
 # Fix this file to avoid intefering with stddef.h.
-
 file=sys/types.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
-  echo Fixing $file comment
+  echo Fixing $file
   ex ${LIB}/$file <<EOF
   /size_t.*;/
   i
-#ifndef _SIZE_T
-#define _SIZE_T
+#ifndef _GCC_SIZE_T
+#define _GCC_SIZE_T
 .
   /size_t/+1
   i
@@ -269,12 +257,10 @@ fi
 # Fix an error in this file: a missing semi-colon at the end of the statsswtch
 # structure definition.
 file=rpcsvc/rstat.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/rpcsvc 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
@@ -292,12 +278,10 @@ fi
 # Fix an error in this file: a missing semi-colon at the end of the nodeent
 # structure definition.
 file=netdnet/dnetdb.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/netdnet 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
@@ -313,15 +297,10 @@ EOF
 fi
 
 # Check for bad #ifdef line (in Ultrix 4.1)
-
 file=sys/file.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    mkdir ${LIB}/rpcsvc 2>&-
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
@@ -337,16 +316,30 @@ EOF
   fi
 fi
 
-# Check for superfluous `static' (in Ultrix 4.2)
+# Remove nested comments created by #endifs in a comment (Ultrix 4.1)
+# Only needed if commenting out junk after #endif.
+#file=signal.h
+#if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+#  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+#  chmod +w ${LIB}/$file 2>/dev/null
+#fi
+#
+#if [ -r ${LIB}/$file ]; then
+#  echo Fixing $file, nested comments
+#  sed -e 's/#endif.*/#endif/' ${LIB}/$file > ${LIB}/${file}.sed
+#  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+#  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+#    echo Deleting ${LIB}/$file\; no fixes were needed.
+#    rm -f ${LIB}/$file
+#  fi
+#fi
 
+# Check for superfluous `static' (in Ultrix 4.2)
 file=machine/cpu.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    mkdir ${LIB}/machine 2>&-
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/machine 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
@@ -368,15 +361,12 @@ EOF
   fi
 fi
 
-# Deal with yet another challenge, this in X11/Xmu.h
+# Incorrect sprintf declaration in X11/Xmu.h
 file=X11/Xmu.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    mkdir ${LIB}/X11 2>&-
-    cp $file ${LIB}/$file >/dev/null 2>&1	\
-    || echo "Can't copy $file"
-    chmod +w ${LIB}/$file
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/X11 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
 
 if [ -r ${LIB}/$file ]; then
@@ -396,149 +386,194 @@ EOF
 fi
 
 # Check for missing ';' in struct
-
 file=netinet/ip.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    mkdir ${LIB}/netinet 2>&-
-    sed -e '/^struct/,/^};/s/}$/};/' $file > ${LIB}/$file
-    cmp $file ${LIB}/$file >/dev/null 2>&1 && rm -f ${LIB}/$file
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/netinet 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file
+  sed -e '/^struct/,/^};/s/}$/};/' ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
   fi
 fi
 
-# Fix the CAT macro in memvar.h.
-
+# Fix the CAT macro in SunOS memvar.h.
 file=pixrect/memvar.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    mkdir ${LIB}/pixrect 2>&-
-    sed -e '/^#define.CAT(a,b)/ i\
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/pixrect 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file
+  sed -e '/^#define.CAT(a,b)/ i\
 #ifdef __STDC__ \
 #define CAT(a,b) a##b\
 #else
 /^#define.CAT(a,b)/ a\
 #endif
-' $file > ${LIB}/$file
-    cmp $file ${LIB}/$file >/dev/null 2>&1 && rm -f ${LIB}/$file
+' ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
   fi
 fi
 
 # Check for yet more missing ';' in struct (in SunOS 4.0.x)
-
 file=rpcsvc/rusers.h
-if [ -r $file ]; then
-  if [ ! -r ${LIB}/$file ]; then
-    mkdir ${LIB}/rpcsvc 2>&-
-    sed -e '/^struct/,/^};/s/_cnt$/_cnt;/' $file > ${LIB}/$file
-    cmp $file ${LIB}/$file >/dev/null 2>&1 && rm -f ${LIB}/$file
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/rpcsvc 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file
+  sed -e '/^struct/,/^};/s/_cnt$/_cnt;/' ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
   fi
 fi
 
 # Fix return type of exit and abort in <stdlib.h> on SunOS 4.1.
-
 file=stdlib.h
-base=`basename $file`
-if [ -r ${LIB}/$file ]; then
-  file_to_fix=${LIB}/$file
-else
-  if [ -r ${INPUT}/$file ]; then
-    file_to_fix=${INPUT}/$file
-  else
-    file_to_fix=""
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
-if [ \! -z "$file_to_fix" ]; then
-  echo Checking $file_to_fix
-  sed 's/int	abort/void	abort/g' $file_to_fix \
-    |  sed 's/int	exit/void	exit/g' > /tmp/$base
-  if cmp $file_to_fix /tmp/$base >/dev/null 2>&1; then \
-    echo No change needed in $file_to_fix
-  else
-    echo Fixed $file_to_fix
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file
+  sed -e 's/int	abort/void	abort/g' \
+  -e 's/int	exit/void	exit/g' ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
     rm -f ${LIB}/$file
-    cp /tmp/$base ${LIB}/$file
   fi
-  rm -f /tmp/$base
 fi
 
 # Fix bogus comment in <locale.h> on SunOS 4.1.
-
 file=locale.h
-base=`basename $file`
-if [ -r ${LIB}/$file ]; then
-  file_to_fix=${LIB}/$file
-else
-  if [ -r ${INPUT}/$file ]; then
-    file_to_fix=${INPUT}/$file
-  else
-    file_to_fix=""
-  fi
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
 fi
-if [ \! -z "$file_to_fix" ]; then
-  echo Checking $file_to_fix
-  sed 's%#endif / \*%#endif /\* %g' $file_to_fix > /tmp/$base
-  if cmp $file_to_fix /tmp/$base >/dev/null 2>&1; then \
-    echo No change needed in $file_to_fix
-  else
-    echo Fixed $file_to_fix
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file
+  sed -e 's%#endif / \*%#endif /\* %g' ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
     rm -f ${LIB}/$file
-    cp /tmp/$base ${LIB}/$file
   fi
-  rm -f /tmp/$base
 fi
 
 # Fix bogus #ifdef in <hsfs/hsfs_spec.h> on SunOS 4.1.
-
 file=hsfs/hsfs_spec.h
-base=`basename $file`
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/hsfs 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
 if [ -r ${LIB}/$file ]; then
-  file_to_fix=${LIB}/$file
-  echo Checking $file_to_fix
-  sed 's/\#ifdef __i386__ || __vax__/\#if __i386__ || __vax__/g' $file_to_fix > /tmp/$base
-  if cmp $file_to_fix /tmp/$base >/dev/null 2>&1; then \
-    echo No change needed in $file_to_fix
-  else
-    echo Fixed $file_to_fix
+  echo Fixing $file
+  sed -e 's/\#ifdef __i386__ || __vax__/\#if __i386__ || __vax__/g' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
     rm -f ${LIB}/$file
-    cp /tmp/$base ${LIB}/$file
   fi
-  rm -f /tmp/$base
 fi
 
 # Fix bogus #ifdef in <hsfs/hsnode.h> on SunOS 4.1.
-
 file=hsfs/hsnode.h
-base=`basename $file`
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/hsfs 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
 if [ -r ${LIB}/$file ]; then
-  file_to_fix=${LIB}/$file
-  echo Checking $file_to_fix
-  sed 's/\#ifdef __i386__ || __sun4c__/\#if __i386__ || __sun4c__/g' $file_to_fix > /tmp/$base
-  if cmp $file_to_fix /tmp/$base >/dev/null 2>&1; then \
-    echo No change needed in $file_to_fix
-  else
-    echo Fixed $file_to_fix
+  echo Fixing $file
+  sed -e 's/\#ifdef __i386__ || __sun4c__/\#if __i386__ || __sun4c__/g' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
     rm -f ${LIB}/$file
-    cp /tmp/$base ${LIB}/$file
   fi
-  rm -f /tmp/$base
 fi
 
 # Fix bogus #ifdef in <hsfs/iso_spec.h> on SunOS 4.1.
-
 file=hsfs/iso_spec.h
-base=`basename $file`
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/hsfs 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
 if [ -r ${LIB}/$file ]; then
-  file_to_fix=${LIB}/$file
-  echo Checking $file_to_fix
-  sed 's/\#ifdef __i386__ || __vax__/\#if __i386__ || __vax__/g' $file_to_fix > /tmp/$base
-  if cmp $file_to_fix /tmp/$base >/dev/null 2>&1; then \
-    echo No change needed in $file_to_fix
-  else
-    echo Fixed $file_to_fix
+  echo Fixing $file
+  sed -e 's/\#ifdef __i386__ || __vax__/\#if __i386__ || __vax__/g' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
     rm -f ${LIB}/$file
-    cp /tmp/$base ${LIB}/$file
   fi
-  rm -f /tmp/$base
+fi
+
+# Incorrect #include in Sony News-OS 3.2.
+file=machine/machparam.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/machine 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file, incorrect \#include
+  sed -e 's@"../machine/endian.h"@<machine/endian.h>@' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
+  fi
+fi
+
+# Multiline comment after typedef on IRIX 4.0.1.
+file=sys/types.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  mkdir ${LIB}/sys 2>/dev/null
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file, comment in the middle of \#ifdef
+  sed -e 's@type of the result@type of the result */@' \
+    -e 's@of the sizeof@/* of the sizeof@' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
+  fi
 fi
 
 echo 'Removing unneeded directories:'
