Auto-Committed-Bash:  ver: 2.2.2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -33,11 +33,14 @@ progname=$0
 
 # Default --srcdir to the directory where the script is found, 
 # if a directory was specified.
-srcdir=`echo $0 | sed 's|/[^/]*$||'`
+# The second sed call is to convert `.//configure' to `./configure'.
+srcdir=`echo $0 | sed 's|//|/|' | sed 's|/[^/]*$||'`
 if [ x$srcdir = x$0 ]
 then
 srcdir=
 fi
+
+host=
 
 remove=rm
 hard_link=ln
@@ -82,13 +85,21 @@ do
      -target=* | --target=* | --targe=* | --targ=* | --tar=* | --ta=* | --t=*)
 	target=`echo $arg | sed 's/-*t[a-z]*=//'`
 	;; 
-     -gas | --gas | --ga | --g)
+     -with-gnu-ld | --with-gnu-ld | --with-gnu-l)
+	gnu_ld=yes
+	;;
+     -gas | --gas | --ga | --g | -with-gnu-as | --with-gnu-as | -with-gnu-a)
         gas=yes
 	;;
      -nfp | --nfp | --nf | --n)
 	nfp=yes
 	;;
+     -with-* | --with-*) ;; #ignored
      -x | --x) ;; # ignored
+     -*)
+	echo "Invalid option \`$arg'" 1>&2
+	exit 1
+	;;
      *)
 # Allow configure HOST TARGET
 	if [ x$host = x ]
@@ -149,6 +160,10 @@ then
 	host=$target
 fi
 
+host_xm_file=
+host_xmake_file=
+host_broken_install=
+
 # Decode the host machine, then the target machine.
 # For the host machine, we save the xm_file variable as host_xm_file;
 # then we decode the target machine and forget everything else
@@ -161,8 +176,14 @@ for machine in $host $target; do
 	cpu_type=
 	xm_file=
 	tm_file=
+	out_file=
 	xmake_file=
 	tmake_file=
+	header_files=
+	# Set this to force installation and use of collect2.
+	use_collect2=
+	# Set this to force use of install.sh.
+	broken_install=
 
 	case $machine in
 	# Support site-specific machine types.
@@ -181,9 +202,11 @@ for machine in $host $target; do
 		;;
 	vax-*-bsd*)			# vaxen running BSD
 		tm_file=vax.h
+		use_collect2=yes
 		;;
 	vax-*-ultrix*)			# vaxen running ultrix
 		tm_file=ultrix.h
+		use_collect2=yes
 		;;
 	vax-*-vms*)			# vaxen running VMS
 		xm_file=xm-vms.h
@@ -201,13 +224,15 @@ for machine in $host $target; do
 #		xm_file=xm-tahoe.h
 #		tm_file=tahoe.h
 #		;;
-	i386-osfrose*)			# 386 using OSF/rose
+	i386-*-osfrose*)		# 386 using OSF/rose
 		tm_file=i386rose.h
 		xmake_file=x-i386rose
 		tmake_file=t-i386rose
+		use_collect2=yes
 		;;
 	i386-sequent-bsd*) 		# 80386 from Sequent
 		xm_file=xm-i386.h
+		use_collect2=yes
 		if [ x$gas = xyes ]
 		then
 			tm_file=seq386gas.h
@@ -215,15 +240,23 @@ for machine in $host $target; do
 			tm_file=seq386.h
 		fi
 		;;
-	i386-*-bsd)
+	i386-*-bsd*)
 		xm_file=xm-i386.h
 		tm_file=i386bsd.h
 		tmake_file=t-libc-ok
+		use_collect2=yes
 		;;
 	i386-*-mach*)
 		xm_file=xm-i386.h
 		tm_file=i386mach.h
 		tmake_file=t-libc-ok
+		use_collect2=yes
+		;;
+	i386-*-sco3.2v4*)	 	# 80386 running SCO 3.2v4 system
+		xm_file=xm-i386sco.h
+		tm_file=i386sco4.h
+		xmake_file=x-i386sco
+		tmake_file=t-i386sco
 		;;
 	i386-*-sco*)		 	# 80386 running SCO system
 		xm_file=xm-i386sco.h
@@ -241,10 +274,12 @@ for machine in $host $target; do
 		tm_file=aix386.h
 		xm_file=xm-aix386.h
 		xmake_file=x-aix386
+		broken_install=yes
 		;;
 	i386-sun-sunos*)		# Sun i386 roadrunner
-		xm_file=xm-i386sun.h
+		xm_file=xm-sun386.h
 		tm_file=i386sun.h
+		use_collect2=yes
 		;;
 	i386-*-sysv4*)			# Intel 80386's running system V.4
 		xm_file=xm-i38v4.h
@@ -262,6 +297,13 @@ for machine in $host $target; do
 		else
 			tm_file=i386v.h
 		fi
+		;;
+	i486-ncr-sysv4*)		# NCR 3000 - i486 running system V.4
+		cpu_type=i386
+		xm_file=xm-i38v4.h
+		xmake_file=x-ncr3000
+		tm_file=i486v4.h
+		tmake_file=t-svr4
 		;;
 	i486-*-sysv4*)			# Intel 80486's running system V.4
 		cpu_type=i386
@@ -283,10 +325,10 @@ for machine in $host $target; do
 		tmake_file=t-svr4
 		;;
 	i860-alliant-*)		# Alliant FX/2800
-		xm_file=xm-i86v4.h
-		xmake_file=x-i860v4
+		xm_file=xm-fx2800.h
+		xmake_file=x-fx2800
 		tm_file=fx2800.h
-		tmake_file=t-svr4
+		tmake_file=t-fx2800
 		;;
 	i860-*-bsd*)
 		if [ x$gas = xyes ]
@@ -295,20 +337,30 @@ for machine in $host $target; do
 		else
 			tm_file=i860b.h
 		fi
+		use_collect2=yes
 		;;
 	sparc-tti-*)
 		tm_file=pbd.h
 		xm_file=xm-pbd.h
+		use_collect2=yes
 		;;
 	sparc-*-sunos4*)
 		tm_file=sparc.h
+		use_collect2=yes
 		;;
 	sparc-*-sunos3*)
 		tm_file=sun4o3.h
+		use_collect2=yes
 		;;
 	sparc-*-sysv4*)
-		xm_file=xm-sparcv4.h
+		xm_file=xm-spcv4.h
 		tm_file=sparcv4.h
+		tmake_file=t-svr4
+		xmake_file=x-sparcv4
+		;;
+	sparc-*-solaris2*)
+		xm_file=xm-spcv4.h
+		tm_file=spc-sol2.h
 		tmake_file=t-svr4
 		xmake_file=x-sparcv4
 		;;
@@ -317,18 +369,40 @@ for machine in $host $target; do
 		xm_file=xm-amix.h
 		xmake_file=x-amix
 		tmake_file=t-svr4
+		header_files=math-68881.h
 		;;
 	m68k-*-sysv4*)			# Motorola m68k's running system V.4
 		tm_file=m68kv4.h
 		xm_file=xm-m68kv4.h
 		xmake_file=x-m68kv4
 		tmake_file=t-svr4
+		header_files=math-68881.h
+		;;
+	m68k-bull-sysv*)		# Bull DPX/2
+		if [ x$gas = xyes ]
+		then
+			tm_file=dpx2g.h
+		else
+			tm_file=dpx2.h
+		fi
+		xm_file=xm-m68kv.h
+		# is this cool ?
+		if [ -d /makesys/kernel/cf/ncl_mr ]; then
+			xmake_file=x-dpx2300
+		elif [ -d /makesys/kernel/cf/ncl_el ]; then
+			xmake_file=x-dpx2200
+		fi
+		xmake_file=${xmake_file:-x-dpx2300}
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-next-*)
 		tm_file=next.h
 		out_file=next.c
 		xm_file=xm-next.h
 		tmake_file=t-next
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-sun-sunos3*)
 		if [ x$nfp = xyes ]
@@ -337,6 +411,8 @@ for machine in $host $target; do
 		else
 			tm_file=sun3o3.h
 		fi
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-sun-sunos*)		# For Sunos 4 (the default).
 		if [ x$nfp = xyes ]
@@ -345,13 +421,19 @@ for machine in $host $target; do
 		else
 			tm_file=sun3.h
 		fi
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-sun-mach*)
 		tm_file=sun3mach.h
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-tti-*)
 		tm_file=pbb.h
 		xm_file=xm-m68kv.h
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-hp-hpux*)	# HP 9000 series 300
 		xm_file=xm-hp320.h
@@ -363,9 +445,14 @@ for machine in $host $target; do
 			xmake_file=x-hp320
 			tm_file=hp320.h
 		fi
+		broken_install=yes
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-hp-bsd*)			# HP 9000/3xx running Berkeley Unix
 		tm_file=hp3bsd.h
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-isi-bsd*)
 		if [ x$nfp = xyes ]
@@ -374,6 +461,8 @@ for machine in $host $target; do
 		else
 			tm_file=isi.h
 		fi
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-sony-bsd*)
 	        xm_file=xm-m68k.h
@@ -383,6 +472,8 @@ for machine in $host $target; do
 		else
 			tm_file=news.h
 		fi
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-altos-sysv*)		   # Altos 3068
 		if [ x$gas = xyes ]
@@ -393,32 +484,52 @@ for machine in $host $target; do
 			echo "The Altos is supported only with the GNU assembler" 1>&2
 			exit 1
 		fi
+		header_files=math-68881.h
 	        ;;
 	m68k-motorola-sysv*)
 		tm_file=mot3300.h
 		xm_file=xm-mot3300.h
+		header_files=math-68881.h
 		;;
-	m68k-crds-unos)
+	m68k-crds-unos*)
 		xm_file=xm-crds.h
 		xmake_file=x-crds
 		tm_file=crds.h
-		install_with_cp=yes
+		broken_install=yes
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-apollo-*)
 		xmake_file=x-apollo68
 		tm_file=apollo68.h
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68k-ncr-sysv*)			# NCR Tower 32 SVR3
 		tm_file=tower-as.h
 		xm_file=xm-tower.h
+		xmake_file=x-tower
+		tmake_file=t-svr3
+		header_files=math-68881.h
+		;;
+	m68k-*-sysv3*)			# Motorola m68k's running system V.3
+		tm_file=m68k.h
+		xm_file=xm-m68kv.h
+		xmake_file=x-m68kv
+		tmake_file=t-svr3
+		header_files=math-68881.h
 		;;
 	m68000-sun-sunos3*)
 		cpu_type=m68k
 		tm_file=sun2.h
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68000-sun-sunos4*)
 		cpu_type=m68k
 		tm_file=sun2o4.h
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68000-hp-hpux*)		# HP 9000 series 300
 		cpu_type=m68k
@@ -431,11 +542,16 @@ for machine in $host $target; do
 			xmake_file=x-hp320
 			tm_file=hp310.h
 		fi
+		broken_install=yes
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68000-hp-bsd*)			# HP 9000/200 running BSD
 		cpu_type=m68k
 		tm_file=hp2bsd.h
 		xmake_file=x-hp2bsd
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68000-att-sysv*)
 		cpu_type=m68k
@@ -446,52 +562,62 @@ for machine in $host $target; do
 		else
 			tm_file=3b1.h
 		fi
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	m68000-convergent-sysv*)
 		cpu_type=m68k
 		xm_file=xm-3b1.h
 		tm_file=ctix.h
+		use_collect2=yes
+		header_files=math-68881.h
 		;;
 	ns32k-encore-osf*)		# Encore with OSF/rose
 		tm_file=encrose.h
 		xmake_file=x-encrose
 		tmake_file=t-encrose
+		use_collect2=yes
 		;;
 	ns32k-sequent-bsd*)
 		tm_file=sequent.h
+		use_collect2=yes
 		;;
 	ns32k-encore-bsd*)
 		tm_file=encore.h
+		use_collect2=yes
 		;;
-	ns32k-ns-genix*)
-		xm_file=xm-genix.h
-		xmake_file=x-genix
-		tm_file=genix.h
-		;;
+# This has not been updated to GCC 2.
+#	ns32k-ns-genix*)
+#		xm_file=xm-genix.h
+#		xmake_file=x-genix
+#		tm_file=genix.h
+#		use_collect2=yes
+#		;;
 	ns32k-merlin-*)
 		tm_file=merlin.h
+		use_collect2=yes
 		;;
 	ns32k-pc532-mach*)
 		tm_file=pc532-mach.h
+		use_collect2=yes
 		;;
 	ns32k-pc532-minix*)
 		tm_file=pc532-min.h
 		xm_file=xm-pc532-min.h
+		use_collect2=yes
 		;;
 	m88k-*-luna*)
 		tm_file=m88kluna.h
-		xmake_file=x-m88kluna
 		tmake_file=t-m88kluna
 		;;
 	m88k-dg-dgux*)
-		xmake_file=x-m88kdgux
-		tmake_file=t-m88k
 		tm_file=m88kdgux.h
+		xmake_file=x-m88kdgux
 		;;
 	m88k-*-sysv4*)
+		tm_file=m88kv4.h
 		xmake_file=x-m88kv4
 		tmake_file=t-m88kv4
-		tm_file=m88kv4.h
 		;;
 	m88k-dolphin-sysv3*)
 		tm_file=m88kdolph.h
@@ -501,6 +627,7 @@ for machine in $host $target; do
 	m88k-*-sysv3*)
 		tm_file=m88kv3.h
 		xm_file=xm-m88kv3.h
+		xmake_file=x-m88kv3
 		;;
 # This hasn't been upgraded to GCC 2.
 #	fx80-alliant-*)			# Alliant FX/80
@@ -512,115 +639,178 @@ for machine in $host $target; do
 	c1-convex-*)			# Convex C1
 		tm_file=convex1.h
 		cpu_type=convex
+		use_collect2=yes
 		;;
 	c2-convex-*)			# Convex C2
 		tm_file=convex2.h
 		cpu_type=convex
+		use_collect2=yes
 		;;
 	c32-convex-*)
 		tm_file=convex32.h	# Convex C32xx
 		cpu_type=convex
+		use_collect2=yes
 		;;
 	c34-convex-*)
 		tm_file=convex34.h	# Convex C34xx
 		cpu_type=convex
+		use_collect2=yes
 		;;
 	c38-convex-*)
 		tm_file=convex38.h	# Convex C38xx
 		cpu_type=convex
+		use_collect2=yes
 		;;
 	mips-sgi-irix4*)		# Mostly like a MIPS.
-		tm_file=iris.h
+		tm_file=iris4.h
 		xm_file=xm-irix4.h
-		install_with_cp=yes
+		broken_install=yes
 		xmake_file=x-iris
+		use_collect2=yes
 		;;
-	mips-sgi*)			# Mostly like a MIPS.
+	mips-sgi-*)			# Mostly like a MIPS.
 		tm_file=iris.h
 		xm_file=xm-iris.h
-		install_with_cp=yes
+		broken_install=yes
 		xmake_file=x-iris
-		;;
-	mips-*-sysv4*)			# MIPS System V.4.
-		tm_file=mips-svr4.h
-		xm_file=xm-umips.h
-		xmake_file=x-mipsv
-		;;
-	mips-*-sysv*)			# MIPS System V.
-		tm_file=mips-sysv.h
-		xm_file=xm-umips.h
-		xmake_file=x-mipsv
-		;;
-	mips-mips-*)			# Default MIPS environment.
-		tm_file=mips.h
+		use_collect2=yes
 		;;
 	mips-dec-ultrix*)		# Decstation.
 		tm_file=decstatn.h
 		tmake_file=t-decstatn
 		xmake_file=x-decstatn
+		use_collect2=yes
 	        ;;
-	mips-dec-osf*)			# Decstation running OSF/1 reference port with OSF/rose.
+	mips-dec-osfrose*)		# Decstation running OSF/1 reference port with OSF/rose.
 		tm_file=decrose.h
 		xmake_file=x-decrose
 		tmake_file=t-decrose
+		use_collect2=yes
+		;;
+	mips-dec-osf*)			# Decstation running OSF/1 as shipped by DIGITAL
+		tm_file=dec-osf1.h
+		xmake_file=x-mips
+		tmake_file=t-decstatn
+		use_collect2=yes
 		;;
 	mips-sony-bsd*)			# Sony NEWS 3600 or risc/news.
 		tm_file=mips-news.h
+		xm_file=xm-mipsbsdn.h
+		use_collect2=yes
 		;;
 	mips-sony-sysv*)		# Sony NEWS 3800 with NEWSOS5.0.
 					# That is based on svr4.
 		# t-svr4 is not right because this system doesn't use ELF.
-		tm_file=mips-news5.h
+		tm_file=mips-n5.h
 		xm_file=xm-mipsnews.h
+		use_collect2=yes
 		;;
 	mips-*-bsd*)			# BSD 4.3 variant of MIPS system.
 		tm_file=mips-bsd.h
+		use_collect2=yes
 	        ;;
-# This port has been upgraded and is almost working.
-# Turn it back on if you would like to help debug it.
-#	pyramid | pyramid-* | pyramid-*)
-#		cpu_type=pyr
-#		tm_file=pyr.h
-#		;;
+	mips-*-sysv4*)			# MIPS System V.4.
+		tm_file=mips-svr4.h
+		xm_file=xm-umips.h
+		xmake_file=x-mipsv
+		use_collect2=yes
+		;;
+	mips-*-sysv*)			# MIPS System V.
+		tm_file=mips-sysv.h
+		xm_file=xm-umips.h
+		xmake_file=x-mipsv
+		use_collect2=yes
+		;;
+	mips-mips-*)			# Default MIPS environment.
+		tm_file=mips.h
+		use_collect2=yes
+		;;
+	pyramid-*-*)
+		cpu_type=pyr
+		tm_file=pyr.h
+		use_collect2=yes
+		;;
 # This hasn't been upgraded to GCC 2.
-#	tron | tron-*)
+#	tron-*-*)
 #		cpu_type=gmicro
 #		tm_file=gmicro.h
+#		use_collect2=yes
 #		;;
 	a29k-*-bsd*)
 		tm_file=a29kunix.h
 		xm_file=xm-a29kunix.h
 		xmake_file=x-a29kunix
+		use_collect2=yes
+		;;
+	a29k-*-*)			# Default a29k environment.
+		use_collect2=yes
 		;;
 	romp-*-aos*)
 		xm_file=xm-romp.h
 		tm_file=romp.h
+		use_collect2=yes
 		;;
 	romp-*-mach*)
 		xm_file=xm-romp.h
 		tm_file=romp.h
 		xmake_file=x-romp-mach
+		use_collect2=yes
 		;;
-	rs6000-*-mach* | rs6000-mach*)
+	rs6000-*-mach*)
 		xm_file=xm-rs6k-m.h
 		tm_file=rs6000-mach.h
-		tmake_file=t-rs6000
+		xmake_file=x-rs6k-mach
+		use_collect2=yes
 		;;
 	rs6000-*)
 		xm_file=xm-rs6000.h
 		tm_file=rs6000.h
-		tmake_file=t-rs6000
+		use_collect2=yes
 		;;
-	hp800-*-bsd* | hp700-*-bsd*)
-		cpu_type=hp800
-		xm_file=xm-hp800.h
-		tm_file=hp800.h
+	hppa1.1-*-bsd*)
+		cpu_type=pa
+		xm_file=xm-pa.h
+		tm_file=pa1.h
+		use_collect2=yes
 		;;
-	hp800-*-hpux* | hp700-*-hpux*)
-		cpu_type=hp800
-		xm_file=xm-hp800.h
-		tm_file=hp800hpux.h
-		xmake_file=x-hp800hpux
+	hppa1.0-*-bsd*)
+		cpu_type=pa
+		xm_file=xm-pa.h
+		tm_file=pa.h
+		use_collect2=yes
+		;;
+	hppa1.1-*-hpux*)
+		cpu_type=pa
+		xm_file=xm-pa.h
+		xmake_file=x-pa-hpux
+		if [ x$gas = xyes ]
+		then
+			tm_file=pa1-ghpux.h
+		else
+			tm_file=pa1-hpux.h
+		fi
+		broken_install=yes
+		use_collect2=yes
+		;;
+	hppa1.0-*-hpux*)
+		cpu_type=pa
+		xm_file=xm-pa.h
+		xmake_file=x-pa-hpux
+		if [ x$gas = xyes ]
+		then
+			tm_file=pa-ghpux.h
+		else
+			tm_file=pa-hpux.h
+		fi
+		broken_install=yes
+		use_collect2=yes
+		;;
+	we32k-att-sysv*)
+		cpu_type=we32k
+		use_collect2=yes
+		;;
+	i960-*-*)			# Default i960 environment.
+		use_collect2=yes
 		;;
 	*)
 		echo "Configuration $machine not recognized" 1>&2
@@ -630,11 +820,17 @@ for machine in $host $target; do
 
 	case $machine in
 	*-*-sysv4*)
-		
 		xmake_try_sysv=x-sysv
 		;;
 	*-*-sysv*)
-		install_with_cp=yes
+		broken_install=yes
+		;;
+	esac
+
+	# No need for collect2 if we have the GNU linker.
+	case x$gnu_ld in 
+	xyes)
+		use_collect2=
 		;;
 	esac
 
@@ -653,14 +849,17 @@ for machine in $host $target; do
 		then xmake_file=x-$cpu_type
 		fi
 		host_xmake_file=$xmake_file
-		host_install_with_cp=$install_with_cp
+		host_broken_install=$broken_install
 		pass1done=yes
 	fi
 done
 
 # Default the target-machine variables that were not explicitly set.
 if [ x$tm_file = x ]
-then tm_file=$target.h; fi
+then tm_file=$cpu_type.h; fi
+
+if [ x$header_files = x ]
+then header_files=; fi
 
 if [ x$xm_file = x ]
 then xm_file=xm-$cpu_type.h; fi
@@ -747,11 +946,35 @@ fi
 
 # Add a definition for INSTALL if system wants one.
 # This substitutes for lots of x-* files.
-if [ x$install_with_cp = x ]
+if [ x$host_broken_install = x ]
 then true
 else
 	rm -f Makefile.xx
-	echo "INSTALL=cp" | cat - Makefile.tem > Makefile.xx
+	sed 's|^INSTALL = .*|INSTALL = $(srcdir)/install.sh -c|' Makefile.tem > Makefile.xx
+	rm -f Makefile.tem
+	mv Makefile.xx Makefile.tem
+fi
+
+# Set EXTRA_HEADERS according to header_files.
+# This substitutes for lots of t-* files.
+if [ x$header_files = x ]
+then true
+else
+	rm -f Makefile.xx
+	sed "s/^EXTRA_HEADERS =/EXTRA_HEADERS = $header_files/" Makefile.tem > Makefile.xx
+	rm -f Makefile.tem
+	mv Makefile.xx Makefile.tem
+fi
+
+# Add a definition of USE_COLLECT2 if system wants one.
+# Also tell toplev.c what to do.
+# This substitutes for lots of t-* files.
+if [ x$use_collect2 = x ]
+then true
+else
+	rm -f Makefile.xx
+	(echo "USE_COLLECT2 = ld"; echo "MAYBE_USE_COLLECT2 = -DUSE_COLLECT2")\
+ 	   | cat - Makefile.tem > Makefile.xx
 	rm -f Makefile.tem
 	mv Makefile.xx Makefile.tem
 fi
diff --git a/fixincludes b/fixincludes
--- a/fixincludes
+++ b/fixincludes
@@ -146,7 +146,7 @@ while [ $# != 0 ]; do
 	  /#[a-z]*if.*[	 (]ns32000/	s/\([^_]\)ns32000/\1__ns32000__/g
 	  /#[a-z]*if.*[	 (]pyr/		s/\([^_]\)pyr/\1__pyr__/g
 	  /#[a-z]*if.*[	 (]is68k/	s/\([^_]\)is68k/\1__is68k__/g
-	  /#define.NULL[ 	]/	i\
+	  /^#define.NULL[ 	]/	i\
 		#undef NULL
 	' $2/$file > $2/$file.sed
 	mv $2/$file.sed $2/$file
@@ -182,7 +182,7 @@ EOF
   fi
 fi
 
-# Fix this Sun file to avoid intefering with stddef.h.
+# Fix this Sun file to avoid interfering with stddef.h.
 file=sys/stdtypes.h
 if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
   cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
@@ -227,7 +227,7 @@ EOF
   fi
 fi
 
-# Fix this file to avoid intefering with stddef.h.
+# Fix this file to avoid interfering with stddef.h.
 file=sys/types.h
 if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
   cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
@@ -237,7 +237,7 @@ fi
 if [ -r ${LIB}/$file ]; then
   echo Fixing $file
   ex ${LIB}/$file <<EOF
-  /size_t.*;/
+  /typedef.*size_t.*;/
   i
 #ifndef _GCC_SIZE_T
 #define _GCC_SIZE_T
@@ -287,7 +287,7 @@ fi
 if [ -r ${LIB}/$file ]; then
   echo Fixing $file, definition of nodeent
   ex ${LIB}/$file <<EOF
-  g/na_addr/s//&;/
+  g/char.*na_addr *$/s//&;/
   wq
 EOF
   if cmp $file ${LIB}/$file >/dev/null 2>&1; then
@@ -455,6 +455,10 @@ fi
 if [ -r ${LIB}/$file ]; then
   echo Fixing $file
   sed -e 's/int	abort/void	abort/g' \
+  -e 's/int	free/void	free/g' \
+  -e 's/char \*	calloc/void \*	calloc/g' \
+  -e 's/char \*	malloc/void \*	malloc/g' \
+  -e 's/char \*	realloc/void \*	realloc/g' \
   -e 's/int	exit/void	exit/g' ${LIB}/$file > ${LIB}/${file}.sed
   rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
   if cmp $file ${LIB}/$file >/dev/null 2>&1; then
@@ -462,6 +466,26 @@ if [ -r ${LIB}/$file ]; then
     rm -f ${LIB}/$file
   fi
 fi
+
+# Fix return type of free and {c,m,re}alloc in <malloc.h> on SunOS 4.1.
+file=malloc.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file
+  sed -e 's/typedef[ 	]char \*	malloc_t/typedef void \*	malloc_t/g' \
+  -e 's/int[ 	][ 	]*free/void	free/g' \
+  ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
+  fi
+fi
+
 
 # Fix bogus comment in <locale.h> on SunOS 4.1.
 file=locale.h
@@ -568,6 +592,84 @@ if [ -r ${LIB}/$file ]; then
   echo Fixing $file, comment in the middle of \#ifdef
   sed -e 's@type of the result@type of the result */@' \
     -e 's@of the sizeof@/* of the sizeof@' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
+  fi
+fi
+
+# Fix non-ANSI memcpy declaration that conflicts with gcc's builtin
+# declaration on Sun OS 4.x.  We must only fix this on Sun OS 4.x, because
+# many other systems have similar text but correct versions of the file.
+# To ensure only Sun's is fixed, we grep for a likely unique string.
+file=memory.h
+if egrep '/\*	@\(#\)memory.h 1.4 88/08/19 SMI; from S5R2 1.2	\*/' $file > /dev/null; then
+  if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+    cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+    chmod +w ${LIB}/$file 2>/dev/null
+  fi
+  if [ -r ${LIB}/$file ]; then
+    echo Replacing $file
+    cat > ${LIB}/$file << EOF
+/* This file was generated by fixincludes */
+#ifndef __memory_h__
+#define __memory_h__
+
+#ifdef __STDC__
+extern void *memccpy();
+extern void *memchr();
+extern void *memcpy();
+extern void *memset();
+#else
+extern char *memccpy();
+extern char *memchr();
+extern char *memcpy();
+extern char *memset();
+#endif /* __STDC__ */
+
+extern int memcmp();
+
+#endif __memory_h__
+EOF
+  fi
+fi
+
+# parameters not const on DECstation Ultrix V4.0.
+file=stdio.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file, non-const arg
+  sed -e 's@perror( char \*__s );@perror( const char *__s );@' \
+      -e 's@fputs( char \*__s,@fputs( const char *__s,@' \
+      -e 's@fopen( char \*__filename, char \*__type );@fopen( const char *__filename, const char *__type );@' \
+      -e 's@fwrite( void \*__ptr,@fwrite( const void *__ptr,@' \
+      -e 's@fscanf( FILE \*__stream, char \*__format,@fscanf( FILE *__stream, const char *__format,@' \
+      -e 's@scanf( char \*__format,@scanf( const char *__format,@' \
+      -e 's@sscanf( char \*__s, char \*__format,@sscanf( const char *__s, const char *__format,@' \
+    ${LIB}/$file > ${LIB}/${file}.sed
+  rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
+  if cmp $file ${LIB}/$file >/dev/null 2>&1; then
+    echo Deleting ${LIB}/$file\; no fixes were needed.
+    rm -f ${LIB}/$file
+  fi
+fi
+
+# parameter to atof not const on DECstation Ultrix V4.0.
+file=math.h
+if [ -r $file ] && [ ! -r ${LIB}/$file ]; then
+  cp $file ${LIB}/$file >/dev/null 2>&1 || echo "Can't copy $file"
+  chmod +w ${LIB}/$file 2>/dev/null
+fi
+
+if [ -r ${LIB}/$file ]; then
+  echo Fixing $file, non-const arg
+  sed -e 's@atof( char \*__nptr );@atof( const char *__nptr );@' \
     ${LIB}/$file > ${LIB}/${file}.sed
   rm -f ${LIB}/$file; mv ${LIB}/${file}.sed ${LIB}/$file
   if cmp $file ${LIB}/$file >/dev/null 2>&1; then
